### ISSUE TITLE
String conversion should always be ISO-8601 compilant

### ISSUE THREAD

**Issue by zkiss** [FasterXML/jackson-datatype-jsr310#13]
Class `InstantSerializer` relies on `toString` implementation of `ZonedDateTime`, which is only ISO-8601 if zone and offset are the same, which is not true for example when BST is active in Europe/London timezone (see the [javadocs](http://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html#toString--)).

`DateTimeFormatter` instances should be used instead to ensure producing ISO compilant output.

**Comment by tommack** [comment]
But without the non-standard part, how do you deserialize back into a ZonedDateTime? For another user, that behavior might be the most important.

**Comment by zkiss** [comment]
@tommack The short answer is that you don't, because ISO does not support timezone information, only offsets. I'd consider timezone (like `Europe/London` not offset, like `-08:00`) serialization a new, yet unimplemented feature.

The long answer is that serialisation of timezone with timestamps is not standardised in ISO-8601. As far as I know jackson is supposed to produce ISO-8601 compatible strings when serializing temporal values to strings. This is good, because it works well with other libraries and languages with no extra effort.

Java 8 has introduced it's own way of including timezone information in the date format. This however breaks interoperability with other technologies which did not do the same - consider the scenario when the server is written in Java 8 and the client is running in the browser, written in JS. It also breaks interoperability between jackson modules, namely https://github.com/FasterXML/jackson-datatype-joda. This is clearly not good, as I believe jackson modules should be compatible with each other when you configure them the same way through the `ObjectMapper`.

Also don't forget the fact that serializing a timestamp in ISO format does not lose time information, only the timezone information; meaning it precisely identifies the moment in time - milli/nanoseconds from epoch if you like. I don't think that is too bad, considering that so far this was not the default behaviour.

The way I would deal with timezone serialization is by introducing a config switch to include/expect it in the date format. Also there is a `JsonFormat` annotation which can be used to control it if needed - even though this module does not appear to support it at the moment.

**Comment by tommack** [comment]
In Java 8, a ZonedDateTime is a very specific thing which, as far as I know, does not have a compatible ISO 8601 representation. Because we can't represent the object according to the standard, there's no clear "right" answer here. 

Your comment at the end about a config switch is the key. Some users may care about strings that are perfectly compatible with ISO 8601 and are willing to *downgrade* the value they're trying to represent, others may care about being able to recreate their ZonedDateTime and are willing to eschew strict standard compatibility. I lean more towards the latter because if I chose to use a ZonedDateTime over an OffsetDateTime, I probably had a good reason.

Just for fun, adding a week to a ZonedDateTime

2015-03-05T12:00-08:00[America/Los_Angeles]
2015-03-12T12:00-07:00[America/Los_Angeles]

and adding a week to an OffsetDateTime

2015-03-05T12:00-08:00
2015-03-12T12:00-08:00

So while the instant in time represented by the first values is the same, what I can do with them is different.

**Comment by zkiss** [comment]
I would accept a different default value for the config switch we are talking about :) - meaning serialising *with* timezone information by default and not losing data during the process.

However I'd still treat interoperability between the joda module and this one as a high priority. And this switch would break that, so the joda module would need changes as well.

On a sidenote I do wonder how the joda module treats the case you mentioned on the example; it only has one `DateTime` class to represent both `OffsetDateTime` and `ZonedDateTime`... If I had to bet I'd probably pick the second case though.

So what happens now?

**Comment by beamerblvd** [comment]
Before I review the code and make comments, I wanted to comment on this issue. Clearly `ZonedDateTimeSerializer` and `ZonedDateTimeDeserializer` need a little extra love here, because `ZonedDateTime` includes information that cannot be represented in standard ISO format and, thus, would be lost in the serialization/deserialization process. I think a configuration switch is key, and I think the default for that switch should result in _no behavioral changes since the last version_.

To be clear, the serializers and deserializers for `Instant` and `OffsetDateTime` should _not change_. These data types do not include time zone information and, thus, can always accurately be represented in standard ISO formats without information loss. I _think_ that's the direction this discussion ultimately went, but I want to make sure we're all on that same page.

**Comment by cowtowncoder** [comment]
@beamerblvd Feedback and help much appreciated here.

**Comment by tommack** [comment]
@beamerblvd, I agree with your summary.

**Comment by cowtowncoder** [comment]
Ok; is it possible to take a subset of changes for which there is no disagreement, and get those checked in first? It would be good to divide-and-conquer if so; then focus on trickier parts.
(apologies if this is obvious -- but just in case there are low-hanging fruits, I'd like to pick them first)

**Comment by zkiss** [comment]
If everyone agrees with my comment on my PR (https://github.com/FasterXML/jackson-datatype-jsr310/pull/15#issuecomment-75154854) then I'd recommend merging the PR as is and introducing the zone preserving feature afterwards.
