### ISSUE TITLE
Add mechanism to configure global per-type `DateTimeFormat` on per-type basis.

### ISSUE THREAD

**Issue by sdeleuze** [FasterXML/jackson-datatype-jsr310#17]
[Like in Joda support](https://github.com/FasterXML/jackson-datatype-joda/blob/master/src/main/java/com/fasterxml/jackson/datatype/joda/ser/DateTimeSerializer.java#L19) support, I think JSR 310 support should allow to customize the format by having [this kind of constructor](https://github.com/FasterXML/jackson-datatype-jsr310/blob/master/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/LocalDateTimeSerializer.java#L44) public.

**Comment by tyoras** [comment]
Yes it will be useful when you need to serialize / deserialize the LocalDate in another format than ISO-8601.

**Comment by jakobbohem** [comment]
Please! I currently have to resort to ugly hacks to get the format to be "yyyy-MM-dd'T'HH:mm:ssXX" instead of "yyyy-MM-dd'T'HH:mm:ssZ" (default)
thanks

**Comment by sandermak** [comment]
On related note, currently the ```LocalDateDeserializer``` fails when provided a string that also includes time. I would like it to be more lenient. Just ignore the time component if we are only interested in deserializing to LocalDate, rather than throwing an error as it does now.

**Comment by cowtowncoder** [comment]
@sandermak Please file a separate issue for changes that are not directly related -- it's fine to add a cross-reference, but anything that may be implemented separately is better to cover via separate issues.

@sdeleuze I am actually not sure what is requested; `LocalDateTimeDeserializer` supports configurable format via `@JsonFormat(pattern=....)` in version 2.5.
Are you referring to other date/time types, or for something else?

**Comment by sandermak** [comment]
@cowtowncoder sure, just created an issue https://github.com/FasterXML/jackson-datatype-jsr310/issues/28 and corresponding PR https://github.com/FasterXML/jackson-datatype-jsr310/pull/27

**Comment by cowtowncoder** [comment]
@sandermak thanks!

**Comment by sdeleuze** [comment]
@cowtowncoder My request is about customizing the format programmatically when configuring globally `JSR310Module` as possible with JodaTime support.

**Comment by cowtowncoder** [comment]
@sdeleuze ok, so in addition to `@JsonFormat`, serializers should allow use of globally specified `java.text.DateFormat`. I was confused by reference to specific piece of code; to me the important part is what feature we are talking about at API level, since sometimes implementations differ.

I updated the title to better reflect the request (I hope).

**Comment by cowtowncoder** [comment]
@sdeleuze Ok, one more finding: since existing global configuration relies on use of `java.text.DateFormat`, which Java Time (JSR-310) does not use, existing configuration method will not work. On the other hand, there is no per-module contextual configuration available either.
So at this point there really isn't much that can be used.

I'll have to re-title this some more, but I think the main idea is still valid; there should be a way to specify default `DateTimeFormatter` to use for types.
One way to make that happen could be to allow per-type registration of `JsonFormat.Value` (contents of which are identical to what `@JsonFormat` contains, but can be constructed programmatically).

**Comment by juplo** [comment]
I think the problem still exists for dezerialization. The constructor of [InstantDeserializer](https://github.com/FasterXML/jackson-datatype-jsr310/blob/master/src/main/java/com/fasterxml/jackson/datatype/jsr310/deser/InstantDeserializer.java#L97) is still not public. Because of that, I can find no way to change the format for deserialization of a type (for example ZonedDateTime) globally.

**Comment by cowtowncoder** [comment]
@juplo at this point your best bet is to sub-class that type, expose constructor that way. Plan is to add a better way to configure formatting aspects for 2.7, so as not to need sub-classing or direct instantiation.

**Comment by cowtowncoder** [comment]
This is now supported via `jackson-databind` "configOverrides" support, which allows specifying `JsonFormat.Value` (which includes support for `pattern`, same as `@JsonFormat` annotation) like so:

```java
        ObjectMapper mapper = newMapper();
        mapper.configOverride(LocalDate.class)
            .setFormat(JsonFormat.Value.forPattern("yyyy_MM_dd"));
```
