### ISSUE TITLE
Support serializing and deserializing Maps with jsr310 types as keys

### ISSUE THREAD

**Issue by zkiss** [FasterXML/jackson-datatype-jsr310#18]
Currently it is not possible to have Java 8 temporal types as keys in maps by default. The module should implement and register `KeySerializers` and `KeyDeserializers` to enable the feature.

These serializers probably should respect `SerializationFeature.WRITE_DATE_KEYS_AS_TIMESTAMPS`. Also there is probably going to be a slight overlap with #13 (serialise timezone or not)

**Comment by beamerblvd** [comment]
Can we get a description for this bug?

**Comment by zkiss** [comment]
Sure, I have updated the initial description. Was going to submit a PR for it, just quickly created an issue as I've noticed it.

**Comment by zkiss** [comment]
@cowtowncoder I think I'll need some help with this one.

It is all done except for the handling of `ZonedDateTime`. For some reason my custom `ZonedDateTimeKeySerializer` is not picked up at all and the time zone information is still serialized (`ZonedDateTime.toString()` is used). Does anyone see any obvious reasons why ([diff](https://github.com/FasterXML/jackson-datatype-jsr310/compare/master...zkiss:key-deserializing))?

**Comment by cowtowncoder** [comment]
Diff is quite sizeable. Which version of databind are you using? Is this for root-level map, or for a map property? In first case, type information for root values may not get passed; and if so, `Map` probably just fetches serializer for `Object`. This is not fault of registered key serializer; it's up to databind. But databind also consider key types to be (more) static than value types -- different discussion.
But what it comes down to is to either pass type info to `ObjectWriter` ("writerFor(type)"), or to only test Map-valued properties.

**Comment by beamerblvd** [comment]
That is a huge diff, and I find it hard to believe there isn't a way for us to accomplish this without adding all these classes. Tatu, you're a lot more familiar with this stuff than I am. What's the deal here? Why doesn't this "just work"?

**Comment by cowtowncoder** [comment]
@beamerblvd Jackson can not use default `JsonSerializer` / `JsonDeserializer` impls by default, due to couple of reasons. So question is what is the best way to package functionality to provide matching `KeyDeserializer`s instances, and suitable `JsonSerializer` (which knows to write `FIELD_NAME`s instead of `VALUE_STRING`s).

If a PR was made I should be able to go through it, get integrated, since this sounds like non-controversial submission.

**Comment by zkiss** [comment]
The changes here are not complete, unfortunately. I have an issue with `ZonedDateTime` serialization - [this](https://github.com/FasterXML/jackson-datatype-jsr310/compare/master...zkiss:key-deserializing#diff-7e117e60e780447dd5f11f33edf5d623R74) test fails.

I want to serialize keys in ISO format. However, when dealing with generic `Map`s, the engine does not treat key types as `ZonedDateTime` (unless explicitly instructed so) and uses the default 'toString()' serializer which I want to avoid. I'd like the module to work out of the box in this case too, however I'm not sure databind supports it.

**Comment by cowtowncoder** [comment]
@zkiss Yes, there are some current issues with serializing of keys of root-value `Map`s unfortunately.
Given this, I think module tests should (for now) test serialization using type-specifying version like:

```java
  String json = mapper.writerFor(new TypeReference<Map<KeyType,ValueType>>() { })
      .writeValueAsString(value);
```

as well as variant that has `Map` as property value. With properties, typing is not needed because full generic type is available from field/method declaration. This is not available for root values.

Question of if and how root-value key type information should work is a bigger one, and I don't know if dynamic typing will ever be supported or not. But it is not modules' fault that behavior doesn't exist, so there is no point in adding tests that expect it at this point.

**Comment by cowtowncoder** [comment]
@zkiss Awesome, thank you for the patch!

This will be in 2.6.0-rc2 (and 2.6.0 final of course), as rc1 was just released yesterday.
