### ISSUE TITLE
Serialize ZonedDateTime and back fails assert

### ISSUE THREAD

**Issue by ctzen** [FasterXML/jackson-datatype-jsr310#22]
This simple test fails, am I doing it wrong?

JDK 1.8.0_40

```groovy
void zonedDateTime() {                                                            
    ObjectMapper mapper = new ObjectMapper()                                      
    mapper.findAndRegisterModules()                                               
    mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)       
    ZonedDateTime x = ZonedDateTime.of(2015, 3, 21, 22, 55, 10, 0, ZoneOffset.UTC)
    Reporter.log(x.toString())                                                    
    String json = mapper.writeValueAsString(x)                                    
    Reporter.log(json)                                                            
    ZonedDateTime y = mapper.readValue(json, ZonedDateTime)                       
    assert x.equals(y)                                                            
}                                                                                 
```
Output:
```
zonedDateTime 	0.029s 	
2015-03-21T22:55:10Z
"2015-03-21T22:55:10Z"
Assertion failed:
assert x.equals(y)
       | |      |
       | false  2015-03-21T22:55:10Z[GMT]
       2015-03-21T22:55:10Z```

**Comment by cowtowncoder** [comment]
Yes, I think that is correct. To ensure the timezone that incoming value has, you need to disable `DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE` like so:

    mapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);

One thing to note is that the underlying Instant (point in time) remains the same in both cases, so it is only question of timezone/offset information being different.

**Comment by vvondra** [comment]
If you're interested that they represent the same time instance, you can use the `isEqual` method
http://stackoverflow.com/questions/25793628/java-8-zoneddatetime-not-equal-another-zoneddatetime

**Comment by seantcanavan** [comment]
This seriously cost me HOURS of debugging. I wasn't sure if it was getting screwed up by my custom DynamoDB object to string mapper, if it was an underlying jackson issue, or if it's just the implementation of ZonedDateTime that was tripping me up. I must've written 6 unit tests when I finally started to understand what was going on with my assertions failing. 

Are we entirely positive this isn't a Jackson issue because ZonedDateTime.parse() correctly returns an identical object but Jackson does not.

`    @Test
    public void zonedDateTimeCorrectlyRestoresItself() {

        // construct a new instance of ZonedDateTime
        ZonedDateTime now = ZonedDateTime.now(ZoneId.of("Z"));
        // offset = {ZoneOffset@3820} "Z"
        // zone   = {ZoneOffset@3820} "Z"

        String starting = now.toString();

        // restore an instance of ZonedDateTime from String
        ZonedDateTime restored = ZonedDateTime.parse(starting);
        // offset = {ZoneOffset@3820} "Z"
        // zone   = {ZoneOffset@3820} "Z"

        assertThat(now).isEqualTo(restored); // ALWAYS succeeds

        System.out.println("test");
    }

    @Test
    public void jacksonIncorrectlyRestoresZonedDateTime() throws Exception {

        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.findAndRegisterModules();

        // construct a new instance of ZonedDateTime
        ZonedDateTime now = ZonedDateTime.now(ZoneId.of("Z"));
        // offset = {ZoneOffset@3820} "Z"
        // zone   = {ZoneOffset@3820} "Z"


        String converted = objectMapper.writeValueAsString(now);

        // restore an instance of ZonedDateTime from String
        ZonedDateTime restored = objectMapper.readValue(converted, ZonedDateTime.class);
        // offset = {ZoneOffset@3820} "Z"
        // zone   = {ZoneOffset@3821} "UTC"

        assertThat(now).isEqualTo(restored); // NEVER succeeds

        System.out.println("break point me");
    }`

**Comment by cowtowncoder** [comment]
@seantcanavan Did you read the preceding discussion, especially my comment on why this appears to occur? Does that not answer your question?

**Comment by seantcanavan** [comment]
Yes I utilized your line of code to configure the mapper and it didn't solve the problem for me. Additionally, I was unable to reproduce the issue of the zone being modified when using the built-in parse functionality of ZonedDateTime and manually marshaling and unmarshaling. Therefore, it **seems** like there should be a way for Jackson to re-build the ZonedDateTime object identically to what it was before since I posted a method myself of how to do exactly that.

While it is easy to verify that the two instances of ZonedDateTime do indeed represent the same instant in time the fact the fact that they are not exactly identical has far reaching implications. 

For instance, when viewing values in our live database they do not appear exactly as I would expect them to because they have been modified by the Jackson code during unmarshaling in an unexpected manner. 

All in all an issue like this is what helps create barriers to adoption for ZonedDateTime when people are already so concretely stuck on JodaTime. It's certainly not helping my case at work for instance. 

I'm far from an expert on the topic but there is definitely room for improvement whether it's in the way Jackson instantiates instances of ZonedDateTime or in the methods of instantiation supported by ZonedDateTime. 

All I'm saying is it shouldn't take someone two hours to debug why an object isn't making a correct round trip through a custom jackson-based serializer and into a database and back only to find out it's because the reasonable assumptions they had made about how the code should operate were in fact wrong.

**Comment by cowtowncoder** [comment]
@seantcanavan Ok: could you please file a new issue with description and full code to reproduce (the reason I asked was that your test did not set configuration I mentioned, so I was guessing you had ignored that) the problem. Also include version(s) tested, and reference (link) to this issue as background.

I think I did test original code included, so it would seem there is some difference; I prefer filing new issues over re-opening old ones, except for minor omissions, because it makes it easier to avoid ambiguities on versions problem was fixed in, detected. 

I agree with you in that it would be good to retain round-trip equality where possible. And it seems it should be possible for `ZonedDateTime` (unlike, say, `java.util.Date` which has... host of problems). So I appreciate your help here, trying to improve Jackson handling of Java 8 datetimes.
Also note that it may make sense to bring this up on mailing list(s) (this could qualify either for user or dev list) -- Java 8 date/time support is one of trickier areas, and has been brought up multiple times. Part of the reason is that I am not an expert here; and people who are tend to have varying amount of time to use for helping with Jackson module (which itself is an external contribution; and very good at that... but quite sizable and does need support due to sheer scope).

**Comment by seantcanavan** [comment]
I appreciate the input @cowtowncoder. I'm willing to help however I can. I'll have some time later in the week to fully explain the issue and exactly how to reproduce it. In the meantime I've updated my code with the most up-to-date unit tests that I was using locally to reproduce the issue - including the line of code you suggested as a fix.

I will also look into using the mailing list as a better way to address the greater jackson community regarding this issue as its resolution is one that I would like to see through for both professional and personal reasons. Strong out-of-the-box support for native java types in jackson will I'm sure make a measurable impact on the java community.

**Comment by cowtowncoder** [comment]
@seantcanavan Excellent! This module is unfortunately bit lacking in current activity (wrt its importance). But it is also a good opportunity to help.

**Comment by seantcanavan** [comment]
For posterity's sake and for anyone else wondering:

Jackson correctly marshals and unmarshals `ZonedDateTime` when the correct `ZoneId` is used. In my specific case it should be `ZoneId.of("UTC")` NOT `ZoneId.of("Z")`

**Comment by poulbildsoe** [comment]
I may have some extra information since I also faced the same problem just now. I found that when using the service loader to load modules (objectMapper.findAndRegisterModules()) the deprecated JSR310Module is still the one being initialized: file jackson-datatype-jsr310/src/main/resources/META-INF/services/com.fasterxml.jackson.databind.Module
I am using the spring Jackson2ObjectMapperBuilder which in fact is able to load JavaTimeModule but will not do so when you instruct it to findModulesViaServiceLoader.
If you register JavaTimeModule then the ZonedDateTime will be written using an ISO-formatter and not toString

**Comment by seantcanavan** [comment]
@poulbildsoe can you provide two small code samples - one instantiating the object mapper incorrectly which produces the wrong result and one instantiating the object mapper correctly and producing the correct result?

**Comment by poulbildsoe** [comment]
I had to think a bit. Maybe the use case actually is quite different but the funny thing is that the test fails for the same reason. The background could be that backend accepts ZonedDateTimes but internally works on LocalDateTimes thus returning ZonedDateTimes in UTC (I got complaints from UI that they didn't expect [UTC] in the returned JSON datetime). 
Really the tests just shows that there is a difference if JavaTimeModule is used or not:

```
@Test
  public void jacksonUsingToStringZonedDateTime() throws IOException  {

      ObjectMapper objectMapper = new ObjectMapper();
      objectMapper.findAndRegisterModules();
      objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS);
      objectMapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS);

      // construct a new instance of ZonedDateTime
      ZonedDateTime incomming = objectMapper.readValue("\"2017-10-30T23:07:47.057Z\"", ZonedDateTime.class);
      // offset = {ZoneOffset@3820} "Z"
      // zone   = {ZoneOffset@3821} "Z"

      LocalDateTime insideServer = incomming.withZoneSameInstant(ZoneId.of("UTC")).toLocalDateTime();

      String converted = objectMapper.writeValueAsString(insideServer.atZone(ZoneId.of("UTC")));

      // restore an instance of ZonedDateTime from String
      ZonedDateTime restored = objectMapper.readValue(converted, ZonedDateTime.class);
      // offset = {ZoneOffset@3820} "Z"
      // zone   = {ZoneOffset@3821} "UTC"

      Assert.assertEquals(incomming, restored); // NEVER succeeds
  }

  @Test
  public void jacksonUsingISOFormatterZonedDateTime() throws IOException  {

      ObjectMapper objectMapper = new ObjectMapper();
      objectMapper.findAndRegisterModules();
      objectMapper.registerModule(new JavaTimeModule());
      objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS);
      objectMapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS);

      // construct a new instance of ZonedDateTime
      ZonedDateTime incomming = objectMapper.readValue("\"2017-10-30T23:07:47.057Z\"", ZonedDateTime.class);

      LocalDateTime insideServer = incomming.withZoneSameInstant(ZoneId.of("UTC")).toLocalDateTime();

      String converted = objectMapper.writeValueAsString(insideServer.atZone(ZoneId.of("UTC")));

      // restore an instance of ZonedDateTime from String
      ZonedDateTime restored = objectMapper.readValue(converted, ZonedDateTime.class);

      Assert.assertEquals(incomming, restored); // Succeeds
  }
```
If  jackson-datatype-jsr310/src/main/resources/META-INF/services/com.fasterxml.jackson.databind.Module is changed to point out JavaTimeModule then we would get the expected result

**Comment by cowtowncoder** [comment]
Note that if there is recurring problem, a new issue should be filed (with a reference back to this one).
