### ISSUE TITLE
Cannot parse Javascript date using LocalDateDeserializer

### ISSUE THREAD

**Issue by jukkasi** [FasterXML/jackson-datatype-jsr310#37]
Change made in https://github.com/FasterXML/jackson-datatype-jsr310/commit/ae8d8356f009b6875439b0bfd37f6677f54ed953#diff-699a3d198b3a2eff8c396b00ae8fcdc7 does not make sense since it effectively destroys the ability to parse date like "2015-07-28T13:53+03:00" using a custom formatter.

In this case DateTimeFormatter.ISO_LOCAL_DATE_TIME is used because of "T" check and it fails since it cannot parse offset info.

**Comment by cowtowncoder** [comment]
Ok. So it should try to keep track of whether formatter used is the default formatter (or, if possible, if formatter contains 'T' in format String?), and only apply the check if that is the case.

Thank you for reporting this, apologies for the problem.

**Comment by jukkasi** [comment]
I'm not sure if it makes sense to check for "T" at all and make assumptions based on that since there could be multiple scenarios where the hardcoded format would fail?

Since you can already define custom formatter on field level or globally (at least this is what I believe at the moment) how about just removing "T" check and let the user choose formatter for his "T" scenarios?

**Comment by cowtowncoder** [comment]
The check is not meant to affect custom formats at all, but to solve

https://github.com/FasterXML/jackson-datatype-jsr310/pull/27

so the issue with custom formats is a side effect, not main goal. Given this, what needs to happen is to either avoid check when custom (non-default) format is used (caller supposedly can fully handle any formatting (s)he wants), or, just check format to try to avoid check.
Default format does not accept timezone information, which is why the original patch was submitted.
