### ISSUE TITLE
ParamConverter for each known data type

### ISSUE THREAD

**Issue by SophiaAceves** [FasterXML/jackson-datatype-jsr310#38]
For each of the known data types (Instant, LocalDate, LocalTime, LocalDateTime, OffsetTime, OffsetDateTime, ...), a ParamConverter should be added. This allows to pass the string representation of the datatype to the URL of a request, such as http://.../resource?date=2007-12-03 (in case of a LocalDate).

See http://docs.oracle.com/javaee/7/api/javax/ws/rs/ext/ParamConverter.html.

**Comment by cowtowncoder** [comment]
Hmmh. Not sure about this, since package suggests this is a JAX-RS feature, and as such bit outside scope of this datatype module. There are further questions as to how would the argument be passed (datatype modules do not have any means to pass it).

But perhaps having a mechanisms for allowing registration would make sense for https://github.com/FasterXML/jackson-jaxrs-providers? Since it has dependency to JAX-RS API, and this feature is meant to support JAX-RS endpoints, it would seem like a more natural place.
There is still the question of how to allow passing of configuration, and that would definitely require support via `MessageBodyReader` and/or `MessageBodyWriter` implementation.
