### ISSUE TITLE
ObjectMapper.setDateFormat() doesn't affect to LocalDateTime

### ISSUE THREAD

**Issue by izeye** [FasterXML/jackson-datatype-jsr310#47]
It would be nice that `ObjectMapper.setDateFormat()` affects to `LocalDateTime` like `java.util.Date`.

The following tests are what I tried:

https://github.com/izeye/samples-java-branches/blob/jackson-jsr310/src/test/java/learningtest/com/fasterxml/jackson/databind/ObjectMapperJsr310Tests.java

**Comment by cowtowncoder** [comment]
I am not sure if this is feasible -- doesnt't "local" mean that no timezone information is to be added?

My plan for 2.7 is to finally add capability to specify per-type defaults for `@JsonFormat` equivalent settings (`JsonFormat.Value` to be exact, one can not construct annotation values themselves), which includes "pattern". With that, it should be possible to define baseline for `LocalDateTime`.
This should make it easier to avoid having to set general global format, which may or may not work with all date/time libs (old `java.util`, Joda, JDK8 date/time).

I mention this idea mostly because it should hopefully provide functionality you want, as well as solve other unrelated issues (default formatting variations for all kinds of types).

**Comment by izeye** [comment]
@cowtowncoder Thanks for the feedback and sorry for the delayed response. I haven't used time zone with formatting, so I didn't consider time zone when I posted this issue. Globally applicable format without time zone like `yyyy-MM-dd HH:mm:ss` across all date and time would be still convenient for me but I'm not sure it's generally useful. Globally applicable format per type like `LocalDateTime` would work for me, so you can close this issue.

**Comment by alechenninger** [comment]
I think this bug is with all java time types. With your same tests, neither ZoneDateTime nor Instant works with the date format from `setDateFormat`.

**Comment by cowtowncoder** [comment]
Looking back there, I forgot to add the obvious statement: `setDateFormat` can not be used by either Joda, or Java 8 date/time. Neither uses "old" JDK `DateFormat`, and as such this can only work for `java.util.Date` and `java.util.Calendar`.

This is a limitation that will not be changed, but I should try to document it in some form.

Instead, there are some facilities for using alternative of `@JsonFormat`, and plan is to add per-type defaulting using similar ideas. This will not be included before Jackson 2.8.

**Comment by alechenninger** [comment]
Thanks for the update!
