### ISSUE TITLE
Fails to deserialize `OffsetDateTime` where format has half-hour timezone offset

### ISSUE THREAD

**Issue by asarkar** [FasterXML/jackson-datatype-jsr310#48]
```
@Test
public void testJacksonOffsetDateTimeDeserializer() throws IOException {
    ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());
    String json = "\"2015-10-20T11:00:00-8:30\"";

    mapper.readValue(json, OffsetDateTime.class); // boom!
}
```

Doesn't help even if I disable `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS`, `DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE` and enable `SerializationFeature.WRITE_DATES_WITH_ZONE_ID`.

Apparently it really wants INSTANT format like `2015-10-20T11:00:00Z`, without the time zone. Which for `OffsetDateTime` is kinda useless because the whole point is to use a time zone (or offset).

**Comment by cowtowncoder** [comment]
Which version? And what is the exception; does it indicate expected textual format to suggest which part if might be having trouble with?

**Comment by abhijitsarkar** [comment]
v2.6.3

```
java.time.format.DateTimeParseException: Text '2015-10-20T11:00:00-8:30' could not be parsed at index 19
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
```

**Comment by zkiss** [comment]
Did a quick test, and this works:
```
@Test
public void testJacksonOffsetDateTimeDeserializer() throws IOException {
  ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());
  String json = "\"2015-10-20T11:00:00-08:30\"";

  mapper.readValue(json, OffsetDateTime.class); // boom!
}
```

Question is is the omission of the leading zero in `-8:30` according to the standard? Apparently `DateTimeFormatter#ISO_OFFSET_DATE_TIME` does not think so.

**Comment by cowtowncoder** [comment]
@zkiss I was guessing that missing zero could be related, although seems odd that format was this strict.

**Comment by abhijitsarkar** [comment]
I checked using all 3 `java.time.format.ResolverStyle` and none worked when the leading zero is missing. You'd think that `ResolverStyle.LENIENT` or `ResolverStyle.SMART` would work while `ResolverStyle.STRICT` might fail, but nops.

Thanks for looking into it.

**Comment by cowtowncoder** [comment]
Ok so use of "partial" timezone offset ("-8:30") is the root cause. But I can not see an example of such value allowed on:

https://en.wikipedia.org/wiki/ISO_8601

although some other alternatives (specifically, only specifying hour, omitting minutes; or leaving it colon) are allowed.

So I suspect that this is not an ISO-8601 compliant notation.

**Comment by mrunelov** [comment]
@cowtowncoder speaking of leaving out the colon, any way to get that to work? It seems like DateTimeFormatter.ISO_OFFSET_DATE_TIME is a bit broken by not using "Z".

**Comment by cowtowncoder** [comment]
I'll let @zkiss and @beamerblvd answer these; I don't know the module well enough.

**Comment by marcelstoer** [comment]
I guess Jackson is right here as the offset has to be ±[hh]:[mm], ±[hh][mm], or ±[hh]. The title of the issue is misleading though as it's got nothing to do with the fact that the zone has a half-hour offset.

What I noticed, though is that `readValue("\"2018-01-12T14:03:00+01\"", ZonedDateTime.class)` fails as well. That's likely a different issue, though.

```java
ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());
mapper.readValue("\"2018-01-12T14:03:00+01\"", ZonedDateTime.class); // fails
mapper.readValue("\"2018-01-12T14:03:00+0100\"", ZonedDateTime.class); // fails
mapper.readValue("\"2018-01-12T14:03:00+01:00\"", ZonedDateTime.class); // works
```

**Context**
I stumbled upon this in the context of a JSON message that has to comply with OpenAPI/Swagger `date-time` which is defined as `("+" / "-") 2-digit hour ":" 2-digit minute` (as per https://tools.ietf.org/html/rfc3339#section-5.6). `+01` is obviously not a valid offset in this context as RFC 3339 is more strict than ISO 8601.

**Comment by cowtowncoder** [comment]
Issues need to move to: https://github.com/FasterXML/jackson-modules-java8/issues
and if there is still follow up this can be re-filed. Just not sure what remains if anything.
