### ISSUE TITLE
Should not leak `DateTimeException`s to caller

### ISSUE THREAD

**Issue by devinrsmith** [FasterXML/jackson-datatype-jsr310#63]
I see that all of the deserializers choose not to catch `java.time.X.parse` exceptions.

For example:

```
    public LocalTime deserialize(JsonParser parser, DeserializationContext context) throws IOException
    {
        if (parser.hasToken(JsonToken.VALUE_STRING)) {
            String string = parser.getText().trim();
            if (string.length() == 0) {
                return null;
            }
            return LocalTime.parse(string, _formatter);
        }
    ...
```

In cases where the string is ill-formatted, `parse` will throw `DateTimeException`s. Is this expected?

I was operating under the assumption that they should be recast as `JsonProcessingException`s. I see this idiom elsewhere when parsing String values:

```
            try {
                return Float.parseFloat(text);
            } catch (IllegalArgumentException iae) { }
            throw ctxt.weirdStringException(text, _valueClass, "not a valid Float value");
```

Should `DateTimeException`s be caught this way by the deserializers?

**Comment by cowtowncoder** [comment]
@devinrsmith Deserializers may or may not catch and rethrow underlying exceptions, since they should typically be caught be surrounding handlers (like `BeanDeserializer`), to do proper wrapping and add information about surrounding object structure (information which individual leaf deserializer does not have access to).
If this is not happening, that is a problem.

**Comment by devinrsmith** [comment]
Hi,

In essence, I'm registering the `JavaTimeModule` with my object mapper and `DateTimeException` exceptions are "escaping".

I'm using the Dropwizard framework. Looking through the stacktrace it looks like we register `io.dropwizard.jersey.jackson.JacksonMessageBodyProvider` which is a simple extension of  `JacksonJaxbJsonProvider`, and this is the sole interface between jersey and jackson.

I'm able to register `ExceptionMapper`s to catch exceptions thrown by the json `MessageBodyReader`. I was expecting to only have to register a mapper of type `ExceptionMapper<JsonProcessingException>` to catch all things remotely related to json errors, but was surprised later to see that `DateTimeException`s were escaping. It's easy enough for me to register a mapper of type `ExceptionMapper<DateTimeException>`, but figured I would check to see if this is expected behavior or not. It seems like it would be better for deserializers to prefer to throw `JsonProcessingException`s. If not, callers have to have thorough / internal knowledge of all possible deserializater's and the errors they may throw for all given types.

**Comment by cowtowncoder** [comment]
@devinrsmith Ok, that does sound like a bug then.

A reproduction for stand-alone test case would be great.

**Comment by cowtowncoder** [comment]
Ah. I see. Yes.

So, the problem is caused by the differences in handling: most usage is expected to occur not directly as root value of type X, but as a property (directly or indirectly) of a POJO, or as contents of `Collection` or value of `Map`. Those failures would be caught.

Since handling of these failures does not yet occur for root values (and there may be complications in getting those done), I went ahead and added direct handling in deserializers. This can be useful in giving out bit more information on failures.

**Comment by cowtowncoder** [comment]
Thank you once again for reporting this and helping pin down issues. Let me know if I missed some cases, should be easy to plug them. I will also try to keep this in mind going forward, for datatypes that favor unchecked exceptions (as those are easier to miss).

**Comment by devinrsmith** [comment]
Thanks for the quick fix. :)
