### ISSUE TITLE
Missing 'TemporalAmountDeserializer'?

### ISSUE THREAD

**Issue by oliverlockwood** [FasterXML/jackson-datatype-jsr310#65]
I'd like to be able to deserialize a `TemporalAmount` from JSON into a Java object.  The catch is that I don't necessarily know in advance whether it's a `Duration` or a `Period`.

It looks like other people have faced the same issue, given the existence of:
-  https://github.com/corbel-platform/lib-ws/blob/master/src/main/java/io/corbel/lib/ws/json/serialization/TemporalAmountJsonDeserializer.java
- http://grepcode.com/file/repo1.maven.org/maven2/com.bq.oss.lib/ws/0.8.0/com/bq/oss/lib/ws/json/serialization/TemporalAmountJsonDeserializer.java

Clearly we could do something similar in our codebase, but it does feel like something that is sufficiently general for there to be library support.  Is there scope for something similar (perhaps only catching a `DateTimeParseException` rather than raw `Exception`) to be built into this library?  If so, I'm happy to raise a PR with new class and appropriate test coverage, but I thought I'd ask first before writing the code in case this has already been discussed and refuted as an idea.

**Comment by cowtowncoder** [comment]
If the issue was just that of what to map `TemporalAmount` to, it's quite easy to specify default implementation to use via `SimpleModule` (method `addAbstractTypeMapping()`). And perhaps module should specify one such mapping to begin with.

If, on the other hand, you have polymorphic use case (may be `Period` or `Duration`), then polymorphic handling, with type ids, is required. There is no way around that.

Now... I am not sure this module can resolve the problem with default settings because in many/most cases users do not want to get additional type information for all `TemporalAmount` serializations, and Jackson is not designed to support ambiguous cases where basetype would enable polymorphic handling, but a subtype would disable it -- this would seem to be against usual expectations of inheritance handling.

**Comment by cowtowncoder** [comment]
Thinking about this bit more (and looking at samples), I don't think default mapping to either of main implementations makes sense. I am also not a big fan of blindly trying out one after the other; I have no problem that being done by users, but does not seem right from library perspective.

So I think that I don't yet see a way to improve default handling: type should be made available by something; either explicit type id, or, in case of specific application, by caller configuring suitable default implementation (or, if they really want, heuristics to try both alternatives as per sample code).

**Comment by oliverlockwood** [comment]
I guess that what bothers me is that the JSON representation of `TemporalAmount` is a standard [ISO8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations), so it feels that this is a common application that should be natively supported by the library.  I appreciate that we may be limited by how Java 8 has implemented ISO8601, as compared with Joda Time's `Period` and `ISOPeriodFormat`, but still...

Could something be introduced which, rather than the try-catch of the sample code, did its own inspection of the string to determine whether a `Period` or `Duration` concrete class should be created, and then used the `Period.parse()` or `Duration.parse()` methods accordingly?

**Comment by cowtowncoder** [comment]
There is no standard representation for `TemporalAmount`: there are representations only for subtypes. That is, there is nothing directly handling values with this type.
If type being handled is declared as `Period` or `Duration`, things work. If `TemporalAmount` is specified, that is ambiguous by definition, and some additional type information must be used.
Conceptually there is no way around that.

To me the problem with usage is not that code does not try to guess what the missing information might be, but that user has to declare it as polymorphic usage.
That is easy enough to do by adding `@JsonTypeInfo` for property in question (either directly or via mix-ins).

**Comment by oliverlockwood** [comment]
@cowtowncoder Apologies if I haven't made myself clear in my earlier comments.  I completely agree that adding @JsonTypeInfo solves things, ***if you can be in control of both sides of the interface***.  It's something I've used for polymorphic cases in the past.

However, we are trying to write the code to consume JSON from an ***external*** service which produces an ISO8601-compliant duration field.  I believe this is a reasonable use case, and as far as I can see there's no way to do this using Jackson, and since JSR310 is Java's implementation of ISO8601, this library seems like the most logical place to introduce such functionality - rather than us just implementing it in our own codebase.

**Comment by cowtowncoder** [comment]
@oliverlockwood If the usage is truly polymorphic, I do not agree that Jackson should try to have special handling for this type for general handling. Especially because adding such handling would make other users angry when their JSON serializations for explicitly typed `Duration` would now have type id always included.

So I think that solution has to be by users of the library. That the type in question is in 3rd party library is not necessarily a blocker (mix-in annotations can solve that), but if the incoming JSON does not have type information, out-of-box polymorphic handling would not really work either.

So if you want "try X first, if it does not map, then Y", it will need to be a custom deserializer, registered by you. I do not want to add such handling.
