### ISSUE TITLE
Can't deserialize Instant from JSON of serialized Date

### ISSUE THREAD

**Issue by lpandzic** [FasterXML/jackson-datatype-jsr310#79]
Hello,

here is the test case (2.7.4):

``` java
@Test
public void should_deserialize_instant_from_serialized_date_in_iso_8601_format() throws IOException {

    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.registerModule(new JavaTimeModule());
    objectMapper.configure(SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS, false);
    objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    objectMapper.configure(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS, false);

    Instant givenInstant = LocalDate.of(2016, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant();
    String json = objectMapper.writeValueAsString(Date.from(givenInstant));

    Instant actual = objectMapper.readValue(json, Instant.class); // this fails

    then(actual).isEqualTo(givenInstant);
}
```

In a scenario where you have a server and client that use Date and want to switch to Instant, it is not possible to do so without breaking backwards compatibilty, e.g. you have to upgrade both at the same time and deploy...

**Comment by cowtowncoder** [comment]
Odd: looks like numeric timezone ("+0000") is frowned upon, but plain zulu notation ("+Z") is accepted.
I added a patch to manually change it if (and only if) using default format pattern for `Instant`. Not sure if that's something Java 8 date pattern itself should handle; or if this is related to `Instant` not expecting timezone or what. 
But for what it is worth, this case now passes. Please let me know if you find related problems.

**Comment by lpandzic** [comment]
I've also detected similar behavior while testing Instant serialization, LocalDateTime serialization and deserialization and ZonedDateTime serialization and deserialization.
Should Date, Instant, LocalDateTime and ZonedDateTime be interchangeable when serializing into or deserializing from non timestamp format (ISO-8601 compliant string)?

**Comment by cowtowncoder** [comment]
@lpandzic I don't know. I am not sure if timezone information is to be considered legal -- "Local" specifically means "no timezone", so I am not quite sure why even 'Z' is allowed. So in that sense types are not interchangeable. I don't know how that would relate to ISO-8601 variations; there are unbounded number of variations that differ wrt which parts are included and/or allowed.
I think it is fair to say that not all combinations do or ever will work directly, without conversion of some sort. And especially so if only using standard pattern definitions.

But I am really hoping someone who knows more about Java Date/Time handling (like @beamerblvd ) can comment here.

**Comment by lpandzic** [comment]
It is not clear what the design intent was behind iso-8601 compatible format, but if one of goals was interoperability then I'd expect every time type that can be serialized to this format to be serialized to this format in same fashion. Also, I'd expect two feature flags: epoch millis/iso 8601 string and offset/zone timezone format.
I assume it is clear how this would work for Date, Instant and ZonedDateTime. LocalDateTime can be serialized and deserialized with Clock/System timezone so the serialized format contains timezone but deserialized doesn't. Behavior would stay the same for all runtimes on same timezone but it would additionaly support runtimes on different timezones.

**Comment by cowtowncoder** [comment]
@lpandzic On first part: I am not sure it is possible to generally claim that there would or should be a single universal textual date/time representation that would work with any and all date/time types. I do agree that making types as inter-operable as possible is a good goal.

I also agree that representation for date-time-with-timezone is easier thing, although even there we have issues of resolution beyond milliseconds: `java.util.Date`, for example, simply has no way to preserve anything more granular.
Come to think of that, `java.util.Date` also has no place to store timezone, so in a way we have at least 3 kinds of date/times:

1. Universal timestamp, but no timezone: `java.util.Date`: for full reliable end-to-end transfer/storage, 64-bit timestamp best
2. Universal, zoned date/time: Joda `DateTime`, JDK8 `ZonedDateTime`, with nanosecond resolution. Can be round-tripped reliably between types in this class, as textual representation. Numeric timestamp trickier due to nanosecond part.
3. Non-zoned date+time (with perhaps nanosecond time?): not representable using timestamp (not universal time); only textual works well, although for numeric value must assume certain timezone (UTC)

Now, then, I don't quite agree with inclusion of timezone for type (3) date/times. If ISO-8601 mandates inclusion of timezone indicator (I thought it does not, but could be wrong -- keep in mind ISO-8601 is a SET of formats, not just single one), then use of `Z` would make sense, although maybe allowing "+0000" is reasonable too. But it would seem best to omit it altogether.

And I actually think that if there was a way to throw an exception if trying to mix (3) with either (1) or (2) that would possible be the best, since such conversions can not really succeed only based on data in json document: they need contextual data, and currently it's debatable if Jackson has that. There is the "default timezone", but I think few users explicitly set it.

Stil, given that even detecting mismatch is difficult, I think that accepting both "Z" and "+0000" for (3) types would be sensible.... yet even with this users are likely to be surprised when during further processing values do not really have timezone (even if textual representation implies there was!).

**Comment by lpandzic** [comment]
Ok, I agree.
So, for offset json values ("+0000"), Instant and OffsetDateTime deserialization should both work?

**Comment by cowtowncoder** [comment]
@lpandzic Yes, there may well be cases to handle. I hope to find time to look into this in future, although what we really need are active owners for this module. I don't think I have enough knowledge to guide the implementation

**Comment by cowtowncoder** [comment]
I added test, extended handling for `OffsetDateTime`. Not sure if anything else is needed for the third related type, `ZonedDateTime`.

**Comment by lpandzic** [comment]
ZonedDateTime has zone, so like you said, I doesn't have to make sense to turn offset into a zone.

**Comment by cowtowncoder** [comment]
@lpandzic right, I thought so. Failure with `OffsetDateTime` actually seems odd (isn't it always expecting an offset) but it is worked around now.

**Comment by lpandzic** [comment]
One more thing before closing this issue. With WRITE_DATES_AS_TIMESTAMPS = false, are Instant and OffsetDateTime serialized into format with offset(same as Date)?

**Comment by lpandzic** [comment]
@cowtowncoder 
Current serialisation behaviour with WRITE_DATES_AS_TIMESTAMPS = false:
Date -> Offset ISO 8601
Instant -> Zoned ISO 8601
OffsetDateTime -> Zoned ISO 8601
Shouldn't all 3 be serialised into Offset ISO 8601?

**Comment by lpandzic** [comment]
I've checked this behavior against JSON-B spec which uses java.time.DateTimeFormatter formatters and it matches the above behavior. At this time I'd rather have compatibility between different jackson versions and future JSON-B than what, at least what seems to me, a more logical json representation of those types.

**Comment by cowtowncoder** [comment]
Ok good to know. I am not really happy with discrepancies in this area, but it is difficult to find a good overall solution. Would be great to have one individual overseeing work across different date/time libraries, as I don't feel competent to oversee that myself.
