### ISSUE TITLE
JSR-310 and jsonSchema issue

### ISSUE THREAD

**Issue by glhf** [FasterXML/jackson-datatype-jsr310#86]
Kotlin Version: 1.0.3
FasterXML Version: 2.7.4

I'm provide JSONSchema generation of  Kotlin's data classes 
Field `activationDate` have LocalDate type 

```      
val objectMapper: ObjectMapper = ObjectMapper()
            .registerKotlinModule()
            .registerModule(JavaTimeModule())
        val jsonSchemaGenerator = JsonSchemaGenerator(objectMapper)
        val schema = jsonSchemaGenerator.generateSchema(Clazz::class.java)
        println(objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(schema))
```

Result  with registration of module

```
...
"activationDate" : {
      "type" : "array",
      "items" : {
        "type" : "integer"
      }
    },
...
```

result without registration of module for jsr-310 

```
...
"activationDate" : {
      "type" : "object",
      "id" : "urn:jsonschema:java:time:LocalDate",
      "properties" : {
        "year" : {
          "type" : "integer"
        },
        "month" : {
          "type" : "string",
          "enum" : [ "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" ]
        },
        "era" : {
          "type" : "object",
          "id" : "urn:jsonschema:java:time:chrono:Era",
          "properties" : {
            "value" : {
              "type" : "integer"
            }
          }
        },
        "dayOfYear" : {
          "type" : "integer"
        },
        "dayOfWeek" : {
          "type" : "string",
          "enum" : [ "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY" ]
        },
        "leapYear" : {
          "type" : "boolean"
        },
        "dayOfMonth" : {
          "type" : "integer"
        },
        "monthValue" : {
          "type" : "integer"
        },
        "chronology" : {
          "type" : "object",
          "id" : "urn:jsonschema:java:time:chrono:IsoChronology",
          "properties" : {
            "calendarType" : {
              "type" : "string"
            },
            "id" : {
              "type" : "string"
            }
          }
        }
      }
    },
...
```

**Comment by cowtowncoder** [comment]
Schema module only knows details of datatypes to the degree Jackson itself does, so in absence of jsr-310 module, date/time types are only seen as POJOs with many getters and setters; the way values would be serialized. When jsr-310 is registered, serialization changes and so does schema.

So the schema produced without module registration is irrelevant in that it can not be very meaningful.

Question is, whether produced schema is compatible with how Jackson serializes given datatypes with datatype supported enabled via module.

Is result you get different from what you expect?

**Comment by glhf** [comment]
I cant understand should JSR-310 make impact to schema generation thats why report it like possible issue. 

So for the Schema generation should I exclude the JSR-310 module usage with schema generation?!

**Comment by cowtowncoder** [comment]
No; `LocalDate` is not supported by `jackson-databind` out of the box (since it depends on Java 6, can not access Java 8 types). All it sees is a POJO with setters/getters, and thereby handles it like any POJO, including schema generation.
So you do need to include jsr-310 module to get handling that "knows" what kind of type `LocalDate` is.

But my question was: what kind of schema would you expect? JSR-310 serializers are responsible for making callbacks, based on active configuration. Defaults for most date/time types are to serialize them as timestamps (numbers); but since `LocalDate` can not be expressed as timestamp (it has no timezone; actual timepoint depends on zone), its default serialization is as an array of integer numbers.
And this is what schema indicates.

So what specifically is your problem?
