### ISSUE TITLE
[2.9] ZonedDateTimeSerializer.class bypass the overridden custom serialize method and returns the default class object

### ISSUE THREAD

**Issue by krunal3224** [FasterXML/jackson-datatype-jsr310#99]
**Need:**

We have multi tenet application where we convert the date based on the timezone of the application, there is no provision in  ZonedDateTimeSerializer to pass time zone and convert it as per the timezone, to solve that we have provided a custom serialize  class which extends functionality of ZonedDateTimeSerializer and converts the date and time based on required timezone.

**Problem and our findings:**

We don't need to override the below methods, but the base class is returning a new object of ZonedDateTimeSerializer which overwrite object created using our extended class. To overcome this, either we need to override the methods or base class can use the factory method to create new instance. In case of override, the method returns object of **JSR310FormattedSerializerBase, but JSR310FormattedSerializerBase class is not public.** This is restricting use to override the methods. Either we make the class JSR310FormattedSerializerBase public or we provide a factory/builder pattern to return object from these methods.

```java
 @Override
    protected JSR310FormattedSerializerBase withFormat(
        Boolean useTimestamp,
        DateTimeFormatter formatter,
        JsonFormat.Shape shape)
  {
        return new ZonedDateTimeSerializer(this, useTimestamp, formatter, _writeZoneId); **// this returns the default serialize object and not the custom one.**

    }



 @Override

    protected JSR310FormattedSerializerBase withFeatures(Boolean writeZoneId) {

        return new ZonedDateTimeSerializer(this, _useTimestamp, _formatter, writeZoneId); **// this returns the default serialize object and not the custom one.**

   }
```

**Comment by cowtowncoder** [comment]
First of all, (de)serializer classes are not designed to be sub-classable: they may allow that or may not, but that is not a design goal. So that's worth keeping in mind.

As to returning non-public type, you should be able to use return type co-variance and need not return `JSR310FormattedSerializerBase` but whatever subtype you have. Compiler will accept such an overload.

Aside from that, what changes would you like to see? I am bit hesitant to make base type public (since I do not really want that to be used for sub-classing), but I am not completely against it.

As to factory methods: adding those is fine, in theory, but as an API change it should ideally go in a new minor version. Problem here is, however, that 2.9 will be the last 2.x release.
Given that, I could consider adding a factory method to be called, if this can be done in backwards compatible manner.
